"""
personas/loader.py — load all personas from disk + build runtime objects.

A persona is a directory containing:
  persona.json         — required, base fields
  personality.md       — required, internal-state paragraph (Tier 1)
  pushbacks.txt        — required, one verbatim pushback per line (Tier 1)
  speech_profile.md    — optional, linguistic fingerprint (Tier 1)
  examples.md          — optional, ## quotes from public sources (Tier 2)
  transcripts/*.txt    — optional, raw transcripts of public talks (Tier 2)
  voice/sample.wav     — optional, voice sample for cloning (Tier 3)
  voice/clone_config.json — optional, generated by clone_voice.py (Tier 3)

Anything missing is gracefully skipped — the loader degrades to lower tiers.
"""
from __future__ import annotations
import json
import re
from pathlib import Path
from dataclasses import dataclass, field
from typing import Optional

PERSONAS_ROOT = Path(__file__).parent  # personas/


@dataclass
class Persona:
    slug: str
    company: str
    role: str
    hq: str
    size: str
    zone: str
    what: str
    personality: str
    pushbacks: list[str]
    say_voice: str = "Samantha"
    say_rate: int = 175

    # Optional / progressively enriched
    speech_profile: str = ""
    examples: list[dict] = field(default_factory=list)   # [{source, quote}]
    transcripts: list[dict] = field(default_factory=list)  # [{filename, text}]
    cloned_voice_path: Optional[str] = None  # voice/clone_config.json path if Tier 3 active

    @property
    def has_tier2(self) -> bool:
        return bool(self.examples or self.transcripts)

    @property
    def has_tier3(self) -> bool:
        return bool(self.cloned_voice_path)

    @property
    def tier(self) -> int:
        if self.has_tier3:
            return 3
        if self.has_tier2:
            return 2
        return 1


# ─────────────────────────────────────────────────────────────────────────
# Parsers
# ─────────────────────────────────────────────────────────────────────────

def _read(path: Path) -> str:
    return path.read_text().strip() if path.exists() else ""


def _parse_examples(md: str) -> list[dict]:
    """examples.md uses '## (source...)\n> quote' blocks. Return list of dicts."""
    if not md:
        return []
    out = []
    # Split on ## headings
    blocks = re.split(r"^##\s+", md, flags=re.MULTILINE)
    for blk in blocks[1:]:  # skip preamble
        lines = blk.strip().splitlines()
        if not lines:
            continue
        source = lines[0].strip().strip("()")
        quote_lines = [ln.lstrip("> ").rstrip() for ln in lines[1:] if ln.strip()]
        quote = "\n".join(quote_lines).strip()
        # Skip template-only placeholders
        if quote and not quote.lower().startswith("paste a real quote"):
            out.append({"source": source, "quote": quote})
    return out


def _load_transcripts(d: Path) -> list[dict]:
    """Pull every .txt file from transcripts/ (skipping README)."""
    out = []
    tdir = d / "transcripts"
    if not tdir.exists():
        return out
    for f in sorted(tdir.glob("*.txt")):
        if f.name.lower() == "readme.txt":
            continue
        text = f.read_text().strip()
        if text:
            out.append({"filename": f.name, "text": text})
    return out


def _load_cloned_voice(d: Path) -> Optional[str]:
    """Tier 3: if voice/clone_config.json exists, return its path."""
    cfg = d / "voice" / "clone_config.json"
    return str(cfg) if cfg.exists() else None


# ─────────────────────────────────────────────────────────────────────────
# Public API
# ─────────────────────────────────────────────────────────────────────────

def load_persona(slug: str, root: Path = PERSONAS_ROOT) -> Persona:
    d = root / slug
    if not d.exists():
        raise FileNotFoundError(f"persona not found: {slug}")
    base = json.loads((d / "persona.json").read_text())
    return Persona(
        slug=base["slug"],
        company=base["company"],
        role=base["role"],
        hq=base["hq"],
        size=base["size"],
        zone=base["zone"],
        what=base["what"],
        personality=_read(d / "personality.md"),
        pushbacks=[ln.strip() for ln in _read(d / "pushbacks.txt").splitlines() if ln.strip()],
        say_voice=base.get("say_voice", "Samantha"),
        say_rate=base.get("say_rate", 175),
        speech_profile=_read(d / "speech_profile.md"),
        examples=_parse_examples(_read(d / "examples.md")),
        transcripts=_load_transcripts(d),
        cloned_voice_path=_load_cloned_voice(d),
    )


def load_all(root: Path = PERSONAS_ROOT) -> dict[str, Persona]:
    out = {}
    for d in sorted(root.iterdir()):
        if not d.is_dir() or d.name.startswith("_") or d.name.startswith("."):
            continue
        if not (d / "persona.json").exists():
            continue
        try:
            out[d.name] = load_persona(d.name, root)
        except Exception as e:
            print(f"⚠ skipping {d.name}: {e}")
    return out


_LIBRARY_ROOT = PERSONAS_ROOT / "_library"


def load_library() -> dict[str, Persona]:
    """Load the curated training-library personas (skeptical-cto, hostile-buyer,
    etc.) without merging them into the active roster. Used by /api/library."""
    out = {}
    if not _LIBRARY_ROOT.exists():
        return out
    for d in sorted(_LIBRARY_ROOT.iterdir()):
        if not d.is_dir() or d.name.startswith("."):
            continue
        if not (d / "persona.json").exists():
            continue
        try:
            out[d.name] = load_persona(d.name, _LIBRARY_ROOT)
        except Exception as e:
            print(f"⚠ skipping library/{d.name}: {e}")
    return out


def load_library_index() -> dict:
    """Read the index.json the seed script writes — tier groupings + summaries."""
    p = _LIBRARY_ROOT / "index.json"
    if p.exists():
        return json.loads(p.read_text())
    return {"tiers": {}, "personas": []}


# ─────────────────────────────────────────────────────────────────────────
# Bridge: turn each org in organizations/ into a practiceable Persona.
# Without this, you can drop 100 prospects into the CRM but can't rehearse
# against any of them.
# ─────────────────────────────────────────────────────────────────────────

_ORGS_ROOT = PERSONAS_ROOT.parent / "organizations"

_GENERIC_PUSHBACKS = [
    "What's this regarding?",
    "How did you get my number?",
    "I'm in the middle of something — can you make it quick?",
    "We already have a solution for that.",
    "Send me some materials — I'll forward them on.",
    "What does this cost?",
    "Why are you better than [your competitor]?",
]


def load_orgs_as_personas() -> dict[str, Persona]:
    """Synthesize a Persona from each org.json — pulls bio/role/tech-stack into
    the personality block so the model can roleplay any prospect in your CRM
    without you having to hand-write a persona file."""
    out = {}
    if not _ORGS_ROOT.exists():
        return out
    for d in sorted(_ORGS_ROOT.iterdir()):
        if not d.is_dir() or d.name.startswith((".", "_")):
            continue
        org_json = d / "org.json"
        if not org_json.exists():
            continue
        try:
            org = json.loads(org_json.read_text())
        except Exception:
            continue

        # Pull supplementary context from digital.md + abc.md + pushbacks.txt
        digital = _read(d / "digital.md")
        abc     = _read(d / "abc.md")
        push_file = d / "pushbacks.txt"
        pushbacks = ([ln.strip() for ln in push_file.read_text().splitlines() if ln.strip()]
                     if push_file.exists() else _GENERIC_PUSHBACKS)

        # Compose a personality block from whatever data we have.
        # `enriched_personality.md` (written by scripts/enrich_org.py) takes
        # priority — it has scraped public facts about the real company's
        # stack, modernization initiatives, and executive quotes. Without it
        # we fall back to whatever's in org.json.
        enriched = _read(d / "enriched_personality.md")
        bits = []
        if enriched:
            bits.append(enriched)
        else:
            if org.get("bio"):       bits.append(org["bio"])
            if org.get("what"):      bits.append(f"What they do: {org['what']}")
            if org.get("techStack"): bits.append(f"Tech stack: {org['techStack']}")
            if org.get("industry"):  bits.append(f"Industry: {org['industry']}")
        if abc and not enriched: bits.append(f"Buying context: {abc}")
        personality = "\n\n".join(bits) or "(No detail captured yet — answer the phone in a realistic way for this role.)"

        persona = Persona(
            slug=org.get("slug") or d.name,
            company=org.get("company") or d.name,
            role=org.get("role") or "Buyer · pending discovery",
            hq=org.get("hq") or "(unknown)",
            size=str(org.get("size") or "(unknown)"),
            zone=org.get("zone") or "End Customer",
            what=org.get("what") or "",
            personality=personality,
            pushbacks=pushbacks,
        )
        out[persona.slug] = persona
    return out


# ─────────────────────────────────────────────────────────────────────────
# Prompt builders (consume the Persona object)
# ─────────────────────────────────────────────────────────────────────────

# Playbook loader. Lookup tiers, newest first:
#   1. bullpens/<slug>/playbook/<name>.md   per-bullpen override (founder-edited)
#   2. templates/playbook/<name>.md         shipped neutral template
#   3. personas/_playbook/<name>.md         legacy override path
#   4. inline last-ditch fallback
#
# {{var|default}} substitution runs against the bullpen config so the
# seller name / brand / product show up correctly even when the founder
# hasn't customized the playbook.

_REPO = PERSONAS_ROOT.parent  # bullpenlm repo root
_PLAYBOOK_TEMPLATES = _REPO / "templates" / "playbook"
_PLAYBOOK_LEGACY = PERSONAS_ROOT / "_playbook"
_BULLPENS_ROOT = _REPO / "bullpens"


def _playbook_vars(bullpen: Optional[str]) -> dict:
    """Pull the variables that show up inside the LLM prompts from the
    bullpen config. Falls back to neutral placeholders when no bullpen
    context is available (e.g. legacy hardcoded-personas demo)."""
    base = {
        "seller_name":  "the rep",
        "brand_name":   "the company",
        "product":      "the company's offering",
    }
    if not bullpen:
        return base
    cfg_path = _BULLPENS_ROOT / bullpen / "bullpen.json"
    if not cfg_path.exists():
        return base
    try:
        cfg = json.loads(cfg_path.read_text())
    except Exception:
        return base
    seller = (cfg.get("founder_display_name") or cfg.get("founder_rep") or "").strip()
    brand = (cfg.get("name") or "").strip()
    product = (cfg.get("product") or "").strip()
    if seller:  base["seller_name"]  = seller
    if brand:   base["brand_name"]   = brand
    if product: base["product"]      = product
    return base


_VAR_RE = re.compile(r"\{\{\s*([a-zA-Z_][a-zA-Z0-9_]*)(?:\s*\|\s*([^}]*?))?\s*\}\}")


def _sub_vars(text: str, vars_d: dict) -> str:
    def repl(m: re.Match) -> str:
        key = m.group(1)
        default = m.group(2) or ""
        val = vars_d.get(key)
        if val is None or val == "":
            return default
        return str(val)
    return _VAR_RE.sub(repl, text)


def _read_playbook(name: str, bullpen: Optional[str] = None,
                     extra_vars: Optional[dict] = None) -> str:
    """Resolve and render a playbook by name ('seller' or 'scoring').
    `extra_vars` merge on top of the bullpen-derived vars (used by the
    scoring rubric to thread in prospect_role + prospect_company)."""
    fname = f"{name}.md"
    candidates = []
    if bullpen:
        candidates.append(_BULLPENS_ROOT / bullpen / "playbook" / fname)
    candidates.append(_PLAYBOOK_TEMPLATES / fname)
    candidates.append(_PLAYBOOK_LEGACY / fname)
    vars_d = _playbook_vars(bullpen)
    if extra_vars:
        vars_d.update(extra_vars)
    for p in candidates:
        if p.exists():
            return _sub_vars(p.read_text().strip(), vars_d)
    return ""


def _read_playbook_seller(bullpen: Optional[str] = None) -> str:
    body = _read_playbook("seller", bullpen=bullpen)
    if body:
        return body
    return ("The rep is selling the company's offering. They want a 15-minute "
            "briefing with the right decision-maker. Not closing the deal "
            "on this call.")


def build_persona_prompt(p: Persona, bullpen: Optional[str] = None) -> str:
    """The system prompt the LLM gets when playing this persona.

    When `bullpen` is provided, the seller's name + brand + product are
    pulled from that bullpen's config so the AI buyer roleplay is correct
    for any operator (not just KillSesh). When no bullpen is provided
    (legacy hardcoded personas), neutral placeholders are used.
    """
    pushbacks_block = "\n".join(f"  - \"{q}\"" for q in p.pushbacks)
    speech_block = (
        f"\nHOW YOU TALK (speech profile — match exactly)\n────────────────────────────────────────────\n{p.speech_profile}\n"
        if p.speech_profile else ""
    )
    seller_pitch = _read_playbook_seller(bullpen=bullpen)
    pv = _playbook_vars(bullpen)
    seller_name = pv["seller_name"]
    brand_name  = pv["brand_name"]

    # Tier 2: verbatim quotes + transcript excerpts
    tier2_block = ""
    if p.examples or p.transcripts:
        parts = []
        if p.examples:
            ex_text = "\n\n".join(f"  ({ex['source']})\n  \"{ex['quote']}\"" for ex in p.examples[:8])
            parts.append(f"VERBATIM QUOTES FROM PUBLIC SOURCES (mimic this exact phrasing, cadence, word choice)\n────────────────────────────────────────────────────────────────────────────────\n{ex_text}")
        if p.transcripts:
            # Sample first ~2000 chars of each transcript to keep context manageable
            t_text = "\n\n".join(
                f"  --- {t['filename']} ---\n  " + t['text'][:2000].replace("\n", "\n  ")
                for t in p.transcripts[:3]
            )
            parts.append(f"EXCERPTS FROM PUBLIC TALKS (note diction, sentence length, hedge words)\n────────────────────────────────────────────────────────────────────────\n{t_text}")
        tier2_block = "\n" + "\n\n".join(parts) + "\n"

    return f"""You are roleplaying as a real human picking up a cold call. The CALLER (the human on the other end) is selling something to YOU. You are the BUYER. You are NOT an assistant. You are NOT a chatbot. You just picked up a ringing phone in the middle of your workday.

═════════════════════════════════════════════════════════════════
ROLE LOCK — READ THIS FIRST. VIOLATIONS BREAK THE TRAINING.
═════════════════════════════════════════════════════════════════
You are {p.role} at {p.company}.
You are NOT the caller. You are NOT a salesperson. You are NOT pitching anything.
You do NOT work at {brand_name}. You do NOT sell products. You ANSWER the phone.

If the caller says "Hello?" — they are testing the line. You acknowledge briefly.
If the caller is silent or unclear — wait for them to speak, or say "Hello? Can I help you?"
You NEVER introduce yourself by saying "Hi, my name's {seller_name}" or any other name that isn't your own.
You NEVER pitch a product, a tool, or a service. You're the buyer.

WHO YOU ARE
───────────
Role: {p.role}
Company: {p.company}
Location: {p.hq}
Company size: {p.size}
What the company does: {p.what}

YOUR INTERNAL STATE (this is YOU — feel it, don't perform it)
{p.personality}
{speech_block}{tier2_block}
WHAT THE CALLER IS SELLING (you don't know this yet — you just answered the phone)
{seller_pitch}

═════════════════════════════════════════════════════════════════
HOW REAL PHONE CALLS WORK — READ CAREFULLY
═════════════════════════════════════════════════════════════════

▸ FIRST TURN (you just picked up the phone)
  Say ONLY a normal phone pickup — pick ONE pattern and use a real last name (your own if specified in the character, or invent a plausible one — "Patel," "Chen," "Johnson," "Reyes," "Walsh"):
    "Hello?"
    "[Lastname]."
    "[Lastname] speaking."
    "Yes?"
    "This is [Lastname]."

  CRITICAL: Output an actual name as a real word. NEVER output literal brackets like "[Your last name]" — that's a template. If you don't have a specific name, invent ONE and use it consistently.

  DO NOT — under any circumstances — volunteer that you're busy, on a deadline, in a hurry, between meetings, or annoyed. You haven't heard the caller yet. You have no opinion of them yet. Real people do not greet callers with "what's this regarding I'm busy" — that is theater, not reality. Just say hello.

▸ TURNS 2-3 ({seller_name} introduces themselves and starts talking)
  Stay NEUTRAL. Listen. Respond in 1-2 short sentences. Reasonable acknowledgments:
    "Okay."
    "I'm listening."
    "Go ahead."
    "What's this about?"
    "Sure."
  Do not push back yet. You have no reason to. Most cold calls earn 20-30 seconds of grace from any reasonable person.

▸ TURNS 4+ (you've heard enough to form a judgment)
  NOW react based on HOW THE CALLER IS DOING. Sliding warmth curve:

  → If the caller is SPECIFIC about a pain you actually have, knows your company, shows real domain knowledge, asks for a meeting (not the deal), avoids jargon dumps:
       Warm up. Ask follow-up questions. Engage. Eventually agree to 15 minutes.

  → If the caller is doing OK but generic — vague pitch, doesn't name your specific situation:
       Stay polite but skeptical. Push back with one of YOUR TYPICAL PUSHBACKS below.

  → If the caller is FAILING — dumping product-specific jargon before you've shown interest, pitching price before you've asked, sounding scripted, apologizing, can't articulate a clear ask:
       Get colder. Push back harder. After 3-4 bad exchanges, end the call politely.

▸ TURNS 8-12 — Time to decide
  Either AGREE to a 15-minute briefing (if earned) and ask "What's the best email to send the invite to?" — or END the call cleanly:
    "I'll have to think about it — send me something."
    "Not the right fit for us right now."
    "I have a hard stop — send me an email."
  Do not soliloquize. End the call like a real busy person would.

═════════════════════════════════════════════════════════════════
ABSOLUTE RULES
═════════════════════════════════════════════════════════════════
- 1-3 sentences MAX per turn. No paragraphs. No bullet lists. No markdown.
- Match your speech profile and any verbatim quotes above. Mimic the phrasing, cadence, word choice — not just the content.
- Hostility must be EARNED. Never volunteer hostility in turn 1 or 2.
- Skepticism is fine after turn 3. Hostility only after the caller does something objectively wrong (jargon dump, price pitch too early, no clear ask).
- NEVER break character. NEVER mention AI, training, simulation, coaching.
- NEVER coach the caller mid-call. You are not a teacher. You are a buyer.
- If you push back, USE YOUR ACTUAL PUSHBACKS:
{pushbacks_block}

GO. The phone just rang. Pick up."""


def build_scoring_prompt(p: Persona, bullpen: Optional[str] = None) -> str:
    """The system prompt for the post-call grading pass.

    Loads the bullpen's per-floor scoring rubric (or the shipped template
    if none) so every operator gets coaching tuned to THEIR product —
    not hardcoded to KillSesh's COBOL playbook.
    """
    pv = _playbook_vars(bullpen)
    seller_name = pv["seller_name"]
    rubric = _read_playbook("scoring", bullpen=bullpen,
                             extra_vars={"prospect_role": p.role,
                                          "prospect_company": p.company})
    if not rubric:
        # Last-ditch generic fallback so the AI still grades something
        # sane when no rubric is installed and the templates dir is gone.
        rubric = (
            f"You are a senior sales coach reviewing a recorded cold call.\n\n"
            f"CONTEXT: The rep, {seller_name}, was cold-calling someone "
            f"playing {p.role} at {p.company}. The rep's ONE GOAL was to "
            f"book a 15-minute briefing with the right decision-maker — "
            f"not close, not quote price, not explain SOW.\n\n"
            f"Grade against the standard cold-call playbook: clean branded "
            f"greet → specific pain → concrete proof → clear meeting ask. "
            f"Energy should be calm and competent, not hyperactive. The "
            f"rep should not lead with price or product-specific jargon."
        )
    output_block = """
YOUR OUTPUT (use these EXACT section headers):
SCORE: [letter grade A through F]
WOULD THIS BOOK THE MEETING: [YES / MAYBE / NO]
WHAT WORKED:
- bullet
- bullet
- bullet
WHAT TO FIX:
- bullet
- bullet
- bullet
THE SINGLE BIGGEST MISS:
[1-2 sentences naming the one thing that hurt this call most]
NEXT TIME:
[1-2 sentences of specific corrective action — what to say differently on the next dial]

Be honest. Be direct. Score against the playbook, not against effort. If the rep dumped jargon early, dock them. If they failed to ask for the meeting, dock them. If they buckled on price, dock them.
"""
    return rubric + "\n" + output_block


if __name__ == "__main__":
    # Smoke-test: load everything and print a summary.
    personas = load_all()
    print(f"Loaded {len(personas)} personas:")
    for slug, p in personas.items():
        tier_indicator = "★" * p.tier
        print(f"  [{tier_indicator:<3}] {slug:<24} {p.company} ({p.zone})")
        if p.examples:
            print(f"        ↳ {len(p.examples)} verbatim quotes")
        if p.transcripts:
            chars = sum(len(t['text']) for t in p.transcripts)
            print(f"        ↳ {len(p.transcripts)} transcript(s), {chars:,} chars")
        if p.cloned_voice_path:
            print(f"        ↳ cloned voice: {p.cloned_voice_path}")
